#!/bin/bash
#give permissions to file
#chmod u+x abduction_algorithm/batch_dubinsrejoin_new_algorithm_w_trimmed.sh
#to execute:
#./abduction_algorithm/batch_dubinsrejoin_new_algorithm_w_trimmed.sh


# add the benchmark name
benchmark_name="dubinsrejoin"

#perturbation size
epsilon=0.7

#inverse weight parameter for epsilon perturbation
weight_parameter=3.5

# the number of input variables of the model
number_of_input_variables=8

#define the root folder
root_folder="/root"

#results_folder
results_parent_folder=$root_folder/"abduction_algorithm/results/new_algorithm_w_trimmed"
results_folder=$results_parent_folder/"w_"$weight_parameter

#create the results folder if it does not already exist
echo "create results folder if it does not exist..."
mkdir -p $results_folder


# create the csv file to store the results
python $root_folder/abduction_algorithm/python_scripts/create_csv.py $number_of_input_variables $benchmark_name $results_folder $epsilon 

#give permissions to access the new algorithm script
chmod u+x $root_folder/abduction_algorithm/new_algorithm_w_trimmed.sh

#change working directory
cd $root_folder/"abduction_algorithm/instances"/$benchmark_name

#get the file names
file_names=$(ls *.vnnlib)

#return to root directory
cd $root_folder

#loop over all the files
for f in $file_names
do
    ./abduction_algorithm/new_algorithm_w_trimmed.sh $benchmark_name $epsilon $number_of_input_variables $root_folder $f $weight_parameter $results_folder
    echo $f
    #remove output file generated by the verifier
    rm $root_folder/out.txt
done
