#!/bin/bash
#give permissions to file
#chmod u+x abduction_algorithm/batch_dubinsrejoin_new_algorithm.sh
#to execute:
#./abduction_algorithm/batch_dubinsrejoin_new_algorithm.sh


# add the benchmark name
benchmark_name="dubinsrejoin"

#perturbation size
epsilon=0.3

# the number of input variables of the model
number_of_input_variables=8

#define the root folder
root_folder="/root"

#results_folder
results_folder=$root_folder/"abduction_algorithm/results/new_algorithm"


# create the csv file to store the results
python $root_folder/abduction_algorithm/python_scripts/create_csv.py $number_of_input_variables $benchmark_name $results_folder $epsilon 

#give permissions to access the new algorithm script
chmod u+x $root_folder/abduction_algorithm/new_algorithm.sh

#change working directory
cd $root_folder/"abduction_algorithm/instances"/$benchmark_name

#get the file names
file_names=$(ls *.vnnlib)

#return to root directory
cd $root_folder

#loop over all the files
for f in $file_names
do
    ./abduction_algorithm/new_algorithm.sh $benchmark_name $epsilon $number_of_input_variables $root_folder $f
    echo $f
    #remove output file generated by the verifier
    rm $root_folder/out.txt
done
