# Configuration file for running the rl_benchmarks benchmark (cartpole model).
general:
  device: cpu
  enable_incomplete_verification: False
  loss_reduction_func: max
  conv_mode: patches
model:
  onnx_path: /root/abduction_algorithm/onnx_models/cartpole.onnx
specification:
  vnnlib_path: /root/abduction_algorithm/abduction_properties/cartpole/cartpole_case_safe_8.vnnlib
solver:
  batch_size: 1  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  branching:
    method: sb  # Split on input space.
    input_split:
      enable: True
attack:
  pgd_order: skip
